[vm-resource-db]
host = "localhost"
port = 
user = 
password = 
dbname = 

[ports]
node = 12401
client = 12402

[virt-server-auto-deallocate]
enabled = true
grace-period = 60

[ipc]
mqueue-path = "/tmp/flyt-rmgr-queue"
frontend-socket = "/tmp/flyt-frontend-socket"